import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Pidgin",
  description: "Terms of use for Pidgin.",
};

const LAST_UPDATED = "June 30, 2025";
const CONTACT_EMAIL = "hello@pidgin.site";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-2xl mx-auto px-6 py-16 sm:py-24">

        {/* Header */}
        <div className="mb-12">
          <a href="/" className="inline-flex items-center gap-2 mb-8 group">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/pidgin-main.png" alt="Pidgin" className="w-6 h-6 rounded-md" />
            <span className="text-sm font-semibold text-muted-foreground group-hover:text-foreground transition-colors">Pidgin</span>
          </a>
          <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated {LAST_UPDATED}</p>
        </div>

        {/* Intro */}
        <div className="mb-10 p-5 rounded-2xl bg-secondary/40 border border-border/50">
          <p className="text-sm leading-relaxed text-foreground/80">
            By using Pidgin, you agree to these terms. We've written them in plain English — no legalese. The short version: use Pidgin for its intended purpose, don't abuse it, and we'll keep building it for you.
          </p>
        </div>

        <div className="space-y-10 text-sm leading-relaxed">

          <section>
            <h2 className="text-base font-semibold mb-3">What Pidgin is</h2>
            <p className="text-foreground/75">Pidgin is a Founder Intelligence System. It connects to your Gmail, reads your newsletter subscriptions, and turns them into a ranked daily brief — what changed, why it matters, and what to do about it — delivered to your inbox. It is currently in invite-only alpha.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Your account</h2>
            <ul className="space-y-2 text-foreground/75">
              <li className="flex gap-2"><span className="text-primary mt-0.5 flex-shrink-0">▸</span><span>You must be invited to use Pidgin during alpha. Sharing your invite link with others is not permitted.</span></li>
              <li className="flex gap-2"><span className="text-primary mt-0.5 flex-shrink-0">▸</span><span>You are responsible for keeping your account secure. Don't share your credentials.</span></li>
              <li className="flex gap-2"><span className="text-primary mt-0.5 flex-shrink-0">▸</span><span>You must be at least 13 years old to use Pidgin.</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Gmail access</h2>
            <p className="text-foreground/75">When you connect Gmail, you grant Pidgin read-only access to identify newsletter emails. We only access newsletters — not personal emails, drafts, or sent mail. You can revoke access at any time from your <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" className="text-primary hover:text-primary/80 transition-colors">Google account settings</a>.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">AI-generated content</h2>
            <p className="text-foreground/75">Summaries, key points, "why it matters" and "what to do" framing, significance ratings, and trend/recurrence detection are all generated by AI and may not be perfectly accurate. They are intended as a convenience, not a replacement for reading the original source. Always refer to the original newsletter for important decisions. Pidgin is not responsible for errors in AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Acceptable use</h2>
            <p className="text-foreground/75 mb-3">You agree not to:</p>
            <ul className="space-y-2 text-foreground/75">
              <li className="flex gap-2"><span className="text-muted-foreground mt-0.5 flex-shrink-0">–</span><span>Attempt to access other users' data</span></li>
              <li className="flex gap-2"><span className="text-muted-foreground mt-0.5 flex-shrink-0">–</span><span>Reverse engineer or scrape the service</span></li>
              <li className="flex gap-2"><span className="text-muted-foreground mt-0.5 flex-shrink-0">–</span><span>Use Pidgin to generate or distribute spam</span></li>
              <li className="flex gap-2"><span className="text-muted-foreground mt-0.5 flex-shrink-0">–</span><span>Overload our systems with automated requests</span></li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Alpha disclaimer</h2>
            <p className="text-foreground/75">Pidgin is in alpha. The service may be unstable, slow, or unavailable at times. Features may change or be removed. We are not liable for any data loss or interruptions during this period. By participating in alpha, you acknowledge this.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Intellectual property</h2>
            <p className="text-foreground/75">Pidgin and its logo are our intellectual property. The newsletter content we summarize belongs to its respective publishers — Pidgin does not claim ownership of any summarized content.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Termination</h2>
            <p className="text-foreground/75">We reserve the right to suspend or terminate accounts that violate these terms. You can delete your account at any time from the dashboard. Upon deletion, your data is removed within 30 days.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Limitation of liability</h2>
            <p className="text-foreground/75">Pidgin is provided "as is." To the extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from your use of the service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Changes to these terms</h2>
            <p className="text-foreground/75">We may update these terms. If the changes are material, we'll notify you by email at least 7 days before they take effect. Continued use of Pidgin after that constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Contact</h2>
            <p className="text-foreground/75">Questions? Email us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary hover:text-primary/80 transition-colors">{CONTACT_EMAIL}</a>.</p>
          </section>

        </div>

        {/* Footer nav */}
        <div className="mt-16 pt-8 border-t border-border/50 flex items-center gap-6 text-xs text-muted-foreground">
          <a href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</a>
          <a href="/dashboard" className="hover:text-foreground transition-colors">Back to app</a>
        </div>

      </div>
    </div>
  );
}
